# 指定markdown渲染器
markdown: kramdown

#网站的主要网址，你可以在这里指定网站的完整URL。
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 23duner's blog
# Description of the Site 既然写博客了 就要考虑可读性
description: 20th Birthday Gift to Myself：互联网冥想盆&项目文件夹

# URL of Image of the Site 
site-image: 
# Keywords of the Site 关键词检索 就是tag吗
site-keywords: 23duner,23墩儿,哈威
# URL for the Image of custom Favicon找一个小logo
favicon-url: /blog_photo/site-image.jpg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /blog_photo/game.jpg  
#只识别/这种
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 23duner@gmail.com

#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
github_username:  23duner
steam_username:  222223duner
bilibili_username:  23墩儿
csdn_username:  23墩儿转码是一种生活方式
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics 某种追踪ID 可以手机有关访问者的数据
google-analytics: UA-163806439-1

# Disqus 指定评论系统
disqus-shortname: thedevslot

# Name of the Author
author-name: Xinyi
# URL for the Image of the Author
author-image: blog_photo/wx_me.jpg
# 60 Words About the Author
author-about: 活到九十九，二到正无穷
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/23duner 我还没有Stack Overflow

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
